

import java.util.*;
import java.lang.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author turha
 */
public class Yatzi extends javax.swing.JFrame {

    /**
     * Creates new form Yatzi
     */
    
    int KastRatt = 0;
    
    public Yatzi() {
        initComponents();
          
    }
    /* public void summa()
    {
                int bir = Integer.parseInt(String.valueOf(txfEttor.getText()));
                int iki = Integer.parseInt(String.valueOf(txfTvor.getText()));
                int uc = Integer.parseInt(String.valueOf(txfTreor.getText()));
                int dort = Integer.parseInt(String.valueOf(txfFyror.getText()));
                int bes = Integer.parseInt(String.valueOf(txfFemmor.getText()));
                int alti = Integer.parseInt(String.valueOf(txfSexor.getText()));
                
                txfSumma.setText(bir+iki+uc+dort+bes+alti+"");
    } */
        public void kastTarning()
        {
            
            if(lblTar1.isEnabled())
                lblTar1.setText(""+(int)(1 + Math.random()*6));
            if(lblTar2.isEnabled())
                lblTar2.setText(""+(int)(1 + Math.random()*6));
            if(lblTar3.isEnabled())
                lblTar3.setText(""+(int)(1 + Math.random()*6));
            if(lblTar4.isEnabled())
                lblTar4.setText(""+(int)(1 + Math.random()*6));
            if(lblTar5.isEnabled())
                lblTar5.setText(""+(int)(1 + Math.random()*6));

                KastRatt++;

                if(KastRatt == 3)
                {
                    btnTarning.setEnabled(false);
                }
                
                
        }
      
        private void Sortera (int[] lista ){
    
        //ska editeras!!!!!!!!!!!!!!!!!
        
        
            if (lista.length < 2) return;
            int temp;

            for (int n = 1; n<lista.length; n++){
                temp = lista [n];
                int i = n - 1;

                while (i >= 0 && lista [i] > temp){
                    lista[i+1] = lista[i]; //Förskjut åt höger
                    i--;
                }
                lista [i+1] = temp;   //Infoga på den tomma platsen
                }

                }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEttor = new javax.swing.JButton();
        btnTvaor = new javax.swing.JButton();
        btnTreor = new javax.swing.JButton();
        btnFyror = new javax.swing.JButton();
        btnFemmor = new javax.swing.JButton();
        btnSexor = new javax.swing.JButton();
        lblTar1 = new javax.swing.JLabel();
        lblTar2 = new javax.swing.JLabel();
        lblTar4 = new javax.swing.JLabel();
        lblTar5 = new javax.swing.JLabel();
        lblTar3 = new javax.swing.JLabel();
        txfTvor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txfEttor = new javax.swing.JTextField();
        txfTreor = new javax.swing.JTextField();
        txfFyror = new javax.swing.JTextField();
        txfFemmor = new javax.swing.JTextField();
        txfSexor = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        btnTarning = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn1par = new javax.swing.JButton();
        btn2par = new javax.swing.JButton();
        btnTreTal = new javax.swing.JButton();
        btnFyraTal = new javax.swing.JButton();
        btnLitenSteg = new javax.swing.JButton();
        btnStorSteg = new javax.swing.JButton();
        btnKak = new javax.swing.JButton();
        btnChans = new javax.swing.JButton();
        btnYatzy = new javax.swing.JButton();
        txfTvopar = new javax.swing.JTextField();
        txfEttpar = new javax.swing.JTextField();
        txfTretal = new javax.swing.JTextField();
        txfFyror1 = new javax.swing.JTextField();
        txfLitenS = new javax.swing.JTextField();
        txfstorS = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txfSumma = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        txfKak = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        txfYatzi = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEttor.setText("ETTOR");
        btnEttor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEttorActionPerformed(evt);
            }
        });

        btnTvaor.setText("TVÅOR");
        btnTvaor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTvaorActionPerformed(evt);
            }
        });

        btnTreor.setText("TREOR");
        btnTreor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreorActionPerformed(evt);
            }
        });

        btnFyror.setText("FYROR");
        btnFyror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFyrorActionPerformed(evt);
            }
        });

        btnFemmor.setText("FEMMOR");
        btnFemmor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFemmorActionPerformed(evt);
            }
        });

        btnSexor.setText("SEXOR");
        btnSexor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSexorActionPerformed(evt);
            }
        });

        lblTar1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTar1.setText("Tärning");
        lblTar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTar1MouseClicked(evt);
            }
        });

        lblTar2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTar2.setText("Tärning");
        lblTar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTar2MouseClicked(evt);
            }
        });

        lblTar4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTar4.setText("Tärning");
        lblTar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTar4MouseClicked(evt);
            }
        });

        lblTar5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTar5.setText("Tärning");
        lblTar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTar5MouseClicked(evt);
            }
        });

        lblTar3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTar3.setText("Tärning");
        lblTar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTar3MouseClicked(evt);
            }
        });

        txfTvor.setEditable(false);
        txfTvor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfTvorActionPerformed(evt);
            }
        });

        jLabel6.setText("Spelare 1");

        jLabel7.setText("Spelare 2");

        txfEttor.setEditable(false);

        txfTreor.setEditable(false);

        txfFyror.setEditable(false);

        txfFemmor.setEditable(false);

        txfSexor.setEditable(false);

        jTextField7.setEditable(false);

        jTextField8.setEditable(false);

        jTextField9.setEditable(false);

        jTextField10.setEditable(false);

        jTextField11.setEditable(false);

        jTextField12.setEditable(false);

        btnTarning.setText("Kasta Tärningarna");
        btnTarning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarningActionPerformed(evt);
            }
        });

        jLabel8.setText("Spelare 1");

        jLabel9.setText("Spelare 2");

        btn1par.setText("1 PAR");
        btn1par.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1parActionPerformed(evt);
            }
        });

        btn2par.setText("2 PAR");
        btn2par.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2parActionPerformed(evt);
            }
        });

        btnTreTal.setText("TRETAL");
        btnTreTal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreTalActionPerformed(evt);
            }
        });

        btnFyraTal.setText("FYRTAL");
        btnFyraTal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFyraTalActionPerformed(evt);
            }
        });

        btnLitenSteg.setText("LITEN STEGE");
        btnLitenSteg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLitenStegActionPerformed(evt);
            }
        });

        btnStorSteg.setText("STOR STEGE");
        btnStorSteg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStorStegActionPerformed(evt);
            }
        });

        btnKak.setText("KÅK");
        btnKak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKakActionPerformed(evt);
            }
        });

        btnChans.setText("CHANS");

        btnYatzy.setText("YATZY");
        btnYatzy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYatzyActionPerformed(evt);
            }
        });

        txfTvopar.setEditable(false);
        txfTvopar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfTvoparActionPerformed(evt);
            }
        });

        txfEttpar.setEditable(false);

        txfTretal.setEditable(false);

        txfFyror1.setEditable(false);

        txfLitenS.setEditable(false);

        txfstorS.setEditable(false);

        jTextField13.setEditable(false);

        jTextField14.setEditable(false);

        jTextField15.setEditable(false);

        jTextField16.setEditable(false);
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });

        jTextField17.setEditable(false);

        jTextField18.setEditable(false);

        jLabel10.setText("Summa");

        jLabel11.setText("Bonus");

        jLabel12.setText("Totalt");

        txfSumma.setEditable(false);
        txfSumma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSummaActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);

        jTextField3.setEditable(false);

        jTextField4.setEditable(false);

        txfKak.setEditable(false);

        jTextField6.setEditable(false);

        jTextField19.setEditable(false);

        jTextField20.setEditable(false);

        txfYatzi.setEditable(false);

        jTextField22.setEditable(false);

        jTextField23.setEditable(false);

        jTextField24.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnFemmor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFyror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTreor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTvaor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEttor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSexor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txfSumma)
                                    .addComponent(txfSexor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfFemmor)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField12)
                                    .addComponent(jTextField11)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txfFyror, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(txfTvor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfEttor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfTreor))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addGap(14, 14, 14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField10)
                                            .addComponent(jTextField9)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblTar1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lblTar2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTar3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(lblTar4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(lblTar5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnStorSteg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLitenSteg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn1par, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn2par, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTreTal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFyraTal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnYatzy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnChans, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txfLitenS, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                            .addComponent(txfFyror1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txfTretal, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txfTvopar)
                                            .addComponent(txfstorS))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jTextField18)
                                            .addComponent(jTextField17)
                                            .addComponent(jTextField16)
                                            .addComponent(jTextField15)
                                            .addComponent(jTextField14)
                                            .addComponent(jTextField13)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfYatzi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfEttpar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfKak, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 37, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(btnTarning)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTar1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTar5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTar4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTar3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTar2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnEttor)
                                            .addComponent(txfEttor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnTvaor)
                                            .addComponent(txfTvor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnTreor)
                                            .addComponent(txfTreor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnFyror)
                                            .addComponent(txfFyror, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnFemmor)
                                            .addComponent(txfFemmor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txfSexor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnSexor)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txfEttpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(3, 3, 3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn1par)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn2par)
                                    .addComponent(txfTvopar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnTreTal)
                                    .addComponent(txfTretal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnFyraTal)
                                    .addComponent(txfFyror1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnLitenSteg)
                                    .addComponent(txfLitenS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnStorSteg)
                                    .addComponent(txfstorS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKak)
                            .addComponent(txfKak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txfSumma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChans)
                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYatzy)
                    .addComponent(txfYatzi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEttorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEttorActionPerformed
        int birinDegeri = 0;
        int bir = Integer.parseInt(String.valueOf(lblTar1.getText()));
        int iki = Integer.parseInt(String.valueOf(lblTar2.getText()));
        int uc = Integer.parseInt(String.valueOf(lblTar3.getText()));
        int dort = Integer.parseInt(String.valueOf(lblTar4.getText()));
        int bes = Integer.parseInt(String.valueOf(lblTar5.getText()));
        
        if(bir == 1)
          birinDegeri++;
        if(iki == 1)
          birinDegeri++;
        if(uc == 1)
          birinDegeri++;
        if(dort == 1)
          birinDegeri++;
        if(bes == 1)
          birinDegeri++;
        
        lblTar1.setEnabled(true);
        lblTar2.setEnabled(true);
        lblTar3.setEnabled(true);
        lblTar4.setEnabled(true);
        lblTar5.setEnabled(true);
        
        if(birinDegeri >= 1)     
        {
            txfEttor.setText(birinDegeri+"");
        }
        else
        {
            txfEttor.setText("/");
        }
        
        KastRatt = 0;
        btnEttor.setEnabled(false);
        btnTarning.setEnabled(true);
        kastTarning();
        
    }//GEN-LAST:event_btnEttorActionPerformed

    private void btn1parActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1parActionPerformed
        int ettPar = 0;
        
        int bir = Integer.parseInt(String.valueOf(lblTar1.getText()));
        int iki = Integer.parseInt(String.valueOf(lblTar2.getText()));
        int uc = Integer.parseInt(String.valueOf(lblTar3.getText()));
        int dort = Integer.parseInt(String.valueOf(lblTar4.getText()));
        int bes = Integer.parseInt(String.valueOf(lblTar5.getText()));
        
        int[] Varden = {bir, iki, uc, dort, bes};
            
        for(int i  = 0; i<Varden.length;i++) 
        {
            for(int j = i+1; j<Varden.length; j++)
            {
                if(Varden[i]==(Varden[j]))
                {
                 ettPar = Varden[i]+Varden[j];  
                 
                
                }
                
            }
        }
           /* for (int i : Varden) 
                if (i == bir || i == iki || i == uc || i == dort || i == bes)
                i = ettPar; */
        
            
                
        lblTar1.setEnabled(true);
        lblTar2.setEnabled(true);
        lblTar3.setEnabled(true);
        lblTar4.setEnabled(true);
        lblTar5.setEnabled(true);
        
        txfEttpar.setText(ettPar+"");
        KastRatt = 0;
        btn1par.setEnabled(false);
        btnTarning.setEnabled(true);
        kastTarning();
    }//GEN-LAST:event_btn1parActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void btnTarningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarningActionPerformed
        kastTarning();
                
                
    }//GEN-LAST:event_btnTarningActionPerformed

    private void lblTar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTar1MouseClicked
        if(lblTar1.isEnabled())
            lblTar1.setEnabled(false);
        else
            lblTar1.setEnabled(true);
    }//GEN-LAST:event_lblTar1MouseClicked

    private void lblTar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTar2MouseClicked
        if(lblTar2.isEnabled())
            lblTar2.setEnabled(false);
        else
            lblTar2.setEnabled(true);    }//GEN-LAST:event_lblTar2MouseClicked

    private void lblTar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTar3MouseClicked
        if(lblTar3.isEnabled())
            lblTar3.setEnabled(false);
        else
            lblTar3.setEnabled(true);    }//GEN-LAST:event_lblTar3MouseClicked

    private void lblTar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTar4MouseClicked
        if(lblTar4.isEnabled())
            lblTar4.setEnabled(false);
        else
            lblTar4.setEnabled(true);    }//GEN-LAST:event_lblTar4MouseClicked

    private void lblTar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTar5MouseClicked
        if(lblTar5.isEnabled())
            lblTar5.setEnabled(false);
        else
            lblTar5.setEnabled(true);    }//GEN-LAST:event_lblTar5MouseClicked

    private void btnTvaorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTvaorActionPerformed
        int ikininDegeri = 0;
        int bir = Integer.parseInt(String.valueOf(lblTar1.getText()));
        int iki = Integer.parseInt(String.valueOf(lblTar2.getText()));
        int uc = Integer.parseInt(String.valueOf(lblTar3.getText()));
        int dort = Integer.parseInt(String.valueOf(lblTar4.getText()));
        int bes = Integer.parseInt(String.valueOf(lblTar5.getText()));
        
        if(bir == 2)
          ikininDegeri = ikininDegeri +2;
        if(iki == 2)
          ikininDegeri = ikininDegeri +2;
        if(uc == 2)
          ikininDegeri = ikininDegeri +2;
        if(dort == 2)
          ikininDegeri = ikininDegeri +2;
        if(bes == 2)
          ikininDegeri = ikininDegeri +2;
        
         lblTar1.setEnabled(true);
        lblTar2.setEnabled(true);
        lblTar3.setEnabled(true);
        lblTar4.setEnabled(true);
        lblTar5.setEnabled(true);
        
        if(ikininDegeri >= 2)     
        {
            txfTvor.setText(ikininDegeri+"");
        }
        else
        {
            txfTvor.setText("/");
        }
        
        KastRatt = 0;
        btnTvaor.setEnabled(false);
        btnTarning.setEnabled(true);
        kastTarning();
    }//GEN-LAST:event_btnTvaorActionPerformed

    private void btnTreorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreorActionPerformed
        int ucundegeri = 0;
        int bir = Integer.parseInt(String.valueOf(lblTar1.getText()));
        int iki = Integer.parseInt(String.valueOf(lblTar2.getText()));
        int uc = Integer.parseInt(String.valueOf(lblTar3.getText()));
        int dort = Integer.parseInt(String.valueOf(lblTar4.getText()));
        int bes = Integer.parseInt(String.valueOf(lblTar5.getText()));
        
        if(bir == 3)
          ucundegeri = ucundegeri +3;
        if(iki == 3)
          ucundegeri = ucundegeri +3;
        if(uc == 3)
          ucundegeri = ucundegeri +3;
        if(dort == 3)
          ucundegeri = ucundegeri +3;
        if(bes == 3)
          ucundegeri = ucundegeri +3;
        
         lblTar1.setEnabled(true);
        lblTar2.setEnabled(true);
        lblTar3.setEnabled(true);
        lblTar4.setEnabled(true);
        lblTar5.setEnabled(true);
        
        if(ucundegeri >= 3)     
        {
            txfTreor.setText(ucundegeri+"");
        }
        else
        {
            txfTreor.setText("/");
        }
        
        KastRatt = 0;
        btnTreor.setEnabled(false);
        btnTarning.setEnabled(true);
        kastTarning();
    }//GEN-LAST:event_btnTreorActionPerformed

    private void btnFyrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFyrorActionPerformed
        int dordunDegeri = 0;
        int bir = Integer.parseInt(String.valueOf(lblTar1.getText()));
        int iki = Integer.parseInt(String.valueOf(lblTar2.getText()));
        int uc = Integer.parseInt(String.valueOf(lblTar3.getText()));
        int dort = Integer.parseInt(String.valueOf(lblTar4.getText()));
        int bes = Integer.parseInt(String.valueOf(lblTar5.getText()));
        
        if(bir == 4)
          dordunDegeri = dordunDegeri +4;
        if(iki == 4)
          dordunDegeri = dordunDegeri +4;
        if(uc == 4)
          dordunDegeri = dordunDegeri +4;
        if(dort == 4)
          dordunDegeri = dordunDegeri +4;
        if(bes == 4)
          dordunDegeri = dordunDegeri +4;
        
         lblTar1.setEnabled(true);
        lblTar2.setEnabled(true);
        lblTar3.setEnabled(true);
        lblTar4.setEnabled(true);
        lblTar5.setEnabled(true);
            //
            if(dordunDegeri >= 4)     
        {
            txfFyror.setText(dordunDegeri+"");
        }
        else
        {
            txfFyror.setText("/");
        }
        
        KastRatt = 0;
        btnFyror.setEnabled(false);
        btnTarning.setEnabled(true);
        kastTarning();
    }//GEN-LAST:event_btnFyrorActionPerformed

    private void btnFemmorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFemmorActionPerformed
        int besindegeri = 0;
        int bir = Integer.parseInt(String.valueOf(lblTar1.getText()));
        int iki = Integer.parseInt(String.valueOf(lblTar2.getText()));
        int uc = Integer.parseInt(String.valueOf(lblTar3.getText()));
        int dort = Integer.parseInt(String.valueOf(lblTar4.getText()));
        int bes = Integer.parseInt(String.valueOf(lblTar5.getText()));
        
        if(bir == 5)
          besindegeri = besindegeri +5;
        if(iki == 5)
          besindegeri = besindegeri +5;
        if(uc == 5)
          besindegeri = besindegeri +5;
        if(dort == 5)
          besindegeri = besindegeri +5;
        if(bes == 5)
          besindegeri = besindegeri +5;
        
         lblTar1.setEnabled(true);
        lblTar2.setEnabled(true);
        lblTar3.setEnabled(true);
        lblTar4.setEnabled(true);
        lblTar5.setEnabled(true);
            //
            if(besindegeri >= 5)     
        {
            txfFemmor.setText(besindegeri+"");
        }
        else
        {
            txfFemmor.setText("/");
        }
        
        KastRatt = 0;
        btnFemmor.setEnabled(false);
        btnTarning.setEnabled(true);
        kastTarning();
    }//GEN-LAST:event_btnFemmorActionPerformed

    private void btnSexorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSexorActionPerformed
        int altinindegeri = 0;
        int bir = Integer.parseInt(String.valueOf(lblTar1.getText()));
        int iki = Integer.parseInt(String.valueOf(lblTar2.getText()));
        int uc = Integer.parseInt(String.valueOf(lblTar3.getText()));
        int dort = Integer.parseInt(String.valueOf(lblTar4.getText()));
        int bes = Integer.parseInt(String.valueOf(lblTar5.getText()));
        
        if(bir == 6)
          altinindegeri = altinindegeri +6;
        if(iki == 6)
          altinindegeri = altinindegeri +6;
        if(uc == 6)
          altinindegeri = altinindegeri +6;
        if(dort == 6)
          altinindegeri = altinindegeri +6;
        if(bes == 6)
          altinindegeri = altinindegeri +6;
        
         lblTar1.setEnabled(true);
        lblTar2.setEnabled(true);
        lblTar3.setEnabled(true);
        lblTar4.setEnabled(true);
        lblTar5.setEnabled(true);
            //
            if(altinindegeri >= 6)     
        {
            txfSexor.setText(altinindegeri+"");
        }
        else
        {
            txfSexor.setText("/");
        }
            
        KastRatt = 0;
        btnSexor.setEnabled(false);
        btnTarning.setEnabled(true);
        kastTarning();
    }//GEN-LAST:event_btnSexorActionPerformed

    private void btn2parActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2parActionPerformed
       int tvoPar = 0;
        
        int bir = Integer.parseInt(String.valueOf(lblTar1.getText()));
        int iki = Integer.parseInt(String.valueOf(lblTar2.getText()));
        int uc = Integer.parseInt(String.valueOf(lblTar3.getText()));
        int dort = Integer.parseInt(String.valueOf(lblTar4.getText()));
        int bes = Integer.parseInt(String.valueOf(lblTar5.getText()));
        
        int[] Varden = {bir, iki, uc, dort, bes};
       
          
            for(int i  = 0; i<Varden.length;i++) 
                    {
                        for(int j = i+1; j<Varden.length; j++)
                        {
                            if((Varden[i])==(Varden[j]))
                            {
                             
                            
                            }
                            
                        }
                    }
                                                
        
            
        lblTar1.setEnabled(true);
        lblTar2.setEnabled(true);
        lblTar3.setEnabled(true);
        lblTar4.setEnabled(true);
        lblTar5.setEnabled(true);
        
        txfTvopar.setText(tvoPar+"");
        KastRatt = 0;
        btn2par.setEnabled(false);
        btnTarning.setEnabled(true);
        kastTarning();
    }//GEN-LAST:event_btn2parActionPerformed

    private void txfTvoparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfTvoparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfTvoparActionPerformed

    private void btnTreTalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreTalActionPerformed
        int treTal = 0;
        int bir = Integer.parseInt(String.valueOf(lblTar1.getText()));
        int iki = Integer.parseInt(String.valueOf(lblTar2.getText()));
        int uc = Integer.parseInt(String.valueOf(lblTar3.getText()));
        int dort = Integer.parseInt(String.valueOf(lblTar4.getText()));
        int bes = Integer.parseInt(String.valueOf(lblTar5.getText()));
        
        int[] Varden = {bir, iki, uc, dort, bes};
            
        for(int i  = 0; i<Varden.length;i++) 
        {
            for(int j = i+1; j<Varden.length; j++)
            {
                for(int k = i+2; k <Varden.length; k++){
                    
                    if(Varden[k] == Varden[i] && Varden[i] == (Varden[j]))
                        {
                         treTal = Varden[i]+Varden[j]+Varden[k];  
                        }
                }
            }
        }
        
        
        
        lblTar1.setEnabled(true);
        lblTar2.setEnabled(true);
        lblTar3.setEnabled(true);
        lblTar4.setEnabled(true);
        lblTar5.setEnabled(true);
        
        txfTretal.setText(treTal+"");
        KastRatt = 0;
        btnTreTal.setEnabled(false);
        btnTarning.setEnabled(true);  
        kastTarning();
    }//GEN-LAST:event_btnTreTalActionPerformed

    private void btnFyraTalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFyraTalActionPerformed
        int fyraTal = 0;
        int bir = Integer.parseInt(String.valueOf(lblTar1.getText()));
        int iki = Integer.parseInt(String.valueOf(lblTar2.getText()));
        int uc = Integer.parseInt(String.valueOf(lblTar3.getText()));
        int dort = Integer.parseInt(String.valueOf(lblTar4.getText()));
        int bes = Integer.parseInt(String.valueOf(lblTar5.getText()));
        
        int[] Varden = {bir, iki, uc, dort, bes};
            
        for(int i  = 0; i<Varden.length;i++) 
        {
            for(int j = i+1; j<Varden.length; j++)
            {
                for(int k = i+2; k <Varden.length; k++){
                    
                    for (int z = i+3; z <Varden.length; z++){
                        if(Varden[k] == Varden[i] && Varden[i] == (Varden[j]))
                        {
                         fyraTal = Varden[z]+Varden[i]+Varden[j]+Varden[k];  


                        }
                    }
                }
            }
        }
        
        
        
        lblTar1.setEnabled(true);
        lblTar2.setEnabled(true);
        lblTar3.setEnabled(true);
        lblTar4.setEnabled(true);
        lblTar5.setEnabled(true);
        
        txfFyror1.setText(fyraTal+"");
        KastRatt = 0;
        btnFyraTal.setEnabled(false);
        btnTarning.setEnabled(true);  
        kastTarning();
    }//GEN-LAST:event_btnFyraTalActionPerformed

    private void btnLitenStegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLitenStegActionPerformed
        int litenSteg = 0;
        int bir = Integer.parseInt(String.valueOf(lblTar1.getText()));
        int iki = Integer.parseInt(String.valueOf(lblTar2.getText()));
        int uc = Integer.parseInt(String.valueOf(lblTar3.getText()));
        int dort = Integer.parseInt(String.valueOf(lblTar4.getText()));
        int bes = Integer.parseInt(String.valueOf(lblTar5.getText()));
        
        int[] Varden = {bir, iki, uc, dort, bes};
        
       
          Sortera ( Varden );
            
             int [] tal = new int[5];
        
            tal[0] = bir;
            tal[1] = iki;
            tal[2] = uc;
            tal[3] = dort;
            tal[4] = bes;
            
            int total = bir+iki+uc+dort+bes;
            
            litenSteg = bir+iki+uc+dort+bes;
        
        lblTar1.setEnabled(true);
        lblTar2.setEnabled(true);
        lblTar3.setEnabled(true);
        lblTar4.setEnabled(true);
        lblTar5.setEnabled(true);
            //
            if(total == 15)
            {
                txfLitenS.setText(litenSteg+"");
            }
            else {txfLitenS.setText("/");}
       
        KastRatt = 0;
        btnLitenSteg.setEnabled(false);
        btnTarning.setEnabled(true);
        kastTarning();
    }//GEN-LAST:event_btnLitenStegActionPerformed

    private void btnStorStegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStorStegActionPerformed
        int storSteg = 0;
        int bir = Integer.parseInt(String.valueOf(lblTar1.getText()));
        int iki = Integer.parseInt(String.valueOf(lblTar2.getText()));
        int uc = Integer.parseInt(String.valueOf(lblTar3.getText()));
        int dort = Integer.parseInt(String.valueOf(lblTar4.getText()));
        int bes = Integer.parseInt(String.valueOf(lblTar5.getText()));
        
        int[] Varden = {bir, iki, uc, dort, bes};
        
       
          Sortera ( Varden );
            
             int [] tal = new int[5];
        
            tal[0] = bir;
            tal[1] = iki;
            tal[2] = uc;
            tal[3] = dort;
            tal[4] = bes;
            
            int total = bir+iki+uc+dort+bes;
            
            storSteg = total;
        
        lblTar1.setEnabled(true);
        lblTar2.setEnabled(true);
        lblTar3.setEnabled(true);
        lblTar4.setEnabled(true);
        lblTar5.setEnabled(true);
            //
            if(total == 20)
            {
                txfstorS.setText(storSteg+"");
            }
            else {txfstorS.setText("/");}
        KastRatt = 0;
        btnStorSteg.setEnabled(false);
        btnTarning.setEnabled(true);
        kastTarning();
    }//GEN-LAST:event_btnStorStegActionPerformed

    private void txfSummaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSummaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfSummaActionPerformed

    private void txfTvorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfTvorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfTvorActionPerformed

    private void btnYatzyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYatzyActionPerformed
       int yatzy = 0;
        int bir = Integer.parseInt(String.valueOf(lblTar1.getText()));
        int iki = Integer.parseInt(String.valueOf(lblTar2.getText()));
        int uc = Integer.parseInt(String.valueOf(lblTar3.getText()));
        int dort = Integer.parseInt(String.valueOf(lblTar4.getText()));
        int bes = Integer.parseInt(String.valueOf(lblTar5.getText()));
        
        int[] Varden = {bir, iki, uc, dort, bes};
            
        for(int i  = 0; i<Varden.length;i++) 
        {
            for(int j = i+1; j<Varden.length; j++)
            {
                for(int k = i+2; k <Varden.length; k++)
                {
                    for (int z = i+3; z <Varden.length; z++)
                    {
                        for (int m =i+4; m<Varden.length; m++)
                        {   
                            
                            if(Varden[j] == Varden[i] && Varden[i] == Varden[k] && Varden[i] == Varden[z] && Varden[i] == (Varden[m]))
                            {
                             yatzy = 50;
                             
                             
                            }
                        }
                    }
                }
            }
        }
        
        
        
        lblTar1.setEnabled(true);
        lblTar2.setEnabled(true);
        lblTar3.setEnabled(true);
        lblTar4.setEnabled(true);
        lblTar5.setEnabled(true);
        
        txfYatzi.setText(yatzy+"");
        KastRatt = 0;
        btnYatzy.setEnabled(false);
        btnTarning.setEnabled(true);  
        kastTarning();
    }//GEN-LAST:event_btnYatzyActionPerformed

    private void btnKakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKakActionPerformed
       int kak = 0;
        
        int bir = Integer.parseInt(String.valueOf(lblTar1.getText()));
        int iki = Integer.parseInt(String.valueOf(lblTar2.getText()));
        int uc = Integer.parseInt(String.valueOf(lblTar3.getText()));
        int dort = Integer.parseInt(String.valueOf(lblTar4.getText()));
        int bes = Integer.parseInt(String.valueOf(lblTar5.getText()));
        
        int[] Varden = {bir, iki, uc, dort, bes};
            
        for(int i  = 0; i<Varden.length;i++) 
        {
            for(int j = i+1; j<Varden.length; j++)
            {
                if(Varden[i]==(Varden[j]))
                {
                 kak = Varden[i]+Varden[j];  
                 
                }
                
                }
               
            }
        
                            for(int m  = 0; m<Varden.length;m++){

                                for(int k = m+1; k<Varden.length; k++)
                                {
                                    for(int t = m+2; t <Varden.length; t++){

                                        if(Varden[t] == (Varden[k]) && Varden[t] == Varden[m] && Varden[k] == Varden[m])
                                            {
                                             kak += Varden[m]+Varden[t]+Varden[k];  
                                            }
                                    }
                                }

                            }  
        
        
            
                
        lblTar1.setEnabled(true);
        lblTar2.setEnabled(true);
        lblTar3.setEnabled(true);
        lblTar4.setEnabled(true);
        lblTar5.setEnabled(true);
        
        txfKak.setText(kak+"");
        KastRatt = 0;
        btnKak.setEnabled(false);
        btnTarning.setEnabled(true);
        kastTarning();
    }//GEN-LAST:event_btnKakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yatzi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yatzi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yatzi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yatzi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Yatzi().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1par;
    private javax.swing.JButton btn2par;
    private javax.swing.JButton btnChans;
    private javax.swing.JButton btnEttor;
    private javax.swing.JButton btnFemmor;
    private javax.swing.JButton btnFyraTal;
    private javax.swing.JButton btnFyror;
    private javax.swing.JButton btnKak;
    private javax.swing.JButton btnLitenSteg;
    private javax.swing.JButton btnSexor;
    private javax.swing.JButton btnStorSteg;
    private javax.swing.JButton btnTarning;
    private javax.swing.JButton btnTreTal;
    private javax.swing.JButton btnTreor;
    private javax.swing.JButton btnTvaor;
    private javax.swing.JButton btnYatzy;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblTar1;
    private javax.swing.JLabel lblTar2;
    private javax.swing.JLabel lblTar3;
    private javax.swing.JLabel lblTar4;
    private javax.swing.JLabel lblTar5;
    private javax.swing.JTextField txfEttor;
    private javax.swing.JTextField txfEttpar;
    private javax.swing.JTextField txfFemmor;
    private javax.swing.JTextField txfFyror;
    private javax.swing.JTextField txfFyror1;
    private javax.swing.JTextField txfKak;
    private javax.swing.JTextField txfLitenS;
    private javax.swing.JTextField txfSexor;
    private javax.swing.JTextField txfSumma;
    private javax.swing.JTextField txfTreor;
    private javax.swing.JTextField txfTretal;
    private javax.swing.JTextField txfTvopar;
    private javax.swing.JTextField txfTvor;
    private javax.swing.JTextField txfYatzi;
    private javax.swing.JTextField txfstorS;
    // End of variables declaration//GEN-END:variables
}
